@startuml Class
!include style.puml

package User {
    User <|-- Administrator
    User <|-- Engineer
    Engineer <|-- Trainer
    Engineer <|-- Learner
    
}

package Course {
    Course *-- Class
    Trainer -- Class
    Engineer -- Class
    Class *-- Chapter
    Class *-- GradedQuiz
    Chapter *-- CourseMaterials
    Chapter *-- UngradedQuiz
    Quiz <|-- GradedQuiz
    Quiz <|-- UngradedQuiz
}

abstract class User #technology {
    - UserID: String
    - UserName: String
    - Password: hash
    - Designation: String
    - Department: String
    + addUser()
    + editUser()
    + deleteUser()
    + searchUser()
}

class Administrator #technology {

}

class Engineer #technology {

}

class Trainer #technology {
    - AssignedCourses: List

}

class Learner #technology {
    - EnrolledCourses: List
    - AttemptedCourses: List
    - CompletedCourses: List
    + SelfEnroll(CourseID): Boolean
}

class Course #technology {
    - CourseID: String
    - CourseName: String
    - CourseDescription: String
    - EnrolledLearners: List
    - PreRequisites: List
}

class Class #technology {
    - ClassID: String
    - ClassName: String
    - StartDate: Date
    - EndDate: Date
    - StartTime: Time
    - EndTime:Time
    - ClassSize: int
    - TrainerName:String
    - MaxEnrollment: int
    - EnrollmentStartDate: Date
    - EnrollmentEndDate: Date
}

class Chapter #technology {
    - SectionID: String
    - SectionName: String
}

class CourseMaterials #technology {
    - Documents: List?
    - Videos: List?
    - Hyperlinks: List
}

abstract class Quiz #technology {
    - QuizID: String
    - QuizName: String
    - QuizDuration: Time
    
}

class GradedQuiz #technology {
    - TotalScore: int
    - LearnerScore: int
}

class UngradedQuiz #technology {

}

class DataAccess #motivation {

}

class Controller #business {

}

class Authenticate #implementation {

}
@enduml