const data = [
  {
    responsive_id: '',
    id: 95,
    course_name: 'Edwina Ebsworth',
    post: 'Human Resources Assistant',
    no_of_classes: 10,
    city: 'Puzi',
    start_date: '10/27/2021',
    end_date: '10/30/2021',
    salary: 19586.23,
    age: '27',
    experience: '2 Years',
    status: 2,
  },
  {
    responsive_id: '',
    id: 1,
    course_name: "Korrie O'Crevy",
    no_of_classes: 9,
    post: 'Nuclear Power Engineer',
    email: 'kocrevy0@thetimes.co.uk',
    city: 'Krasnosilka',
    start_date: '09/23/2021',
    end_date: '09/26/2021',
    salary: 23896.35,
    age: '61',
    experience: '1 Year',
    status: 1,
  },
  {
    responsive_id: '',
    id: 7,
    course_name: 'Eileen Diehn',
    no_of_classes: 8,
    post: 'Environmental Specialist',
    email: 'ediehn6@163.com',
    city: 'Lampuyang',
    start_date: '09/15/2021',
    end_date: '09/18/2021',
    salary: 18991.67,
    age: '59',
    experience: '9 Years',
    status: 1,
  },
]

export default data
